# Generated by Django 5.2.6 on 2025-09-09 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='roo',
            new_name='room',
        ),
    ]
